"""
Pre-build step: gzip webapp/index.html into include/WebPage.h.

webapp/index.html stays the single source of truth for the UI - this only
packs it so the ESP32 can serve it over Wi-Fi. Regenerated on every build.
"""
Import("env")

import gzip
import os

PROJ = env["PROJECT_DIR"]
SRC  = os.path.join(PROJ, "webapp", "index.html")
DST  = os.path.join(PROJ, "include", "WebPage.h")


def build_header():
    with open(SRC, "rb") as f:
        raw = f.read()
    packed = gzip.compress(raw, 9)

    lines = [
        "/* AUTO-GENERATED by scripts/embed_webapp.py - do not edit.",
        " * Source: webapp/index.html  (%d bytes -> %d gzipped)" % (len(raw), len(packed)),
        " */",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "#define WEBPAGE_GZ_LEN %d" % len(packed),
        "",
        "static const uint8_t WEBPAGE_GZ[] PROGMEM = {",
    ]
    for i in range(0, len(packed), 16):
        chunk = packed[i:i + 16]
        lines.append("    " + "".join("0x%02X," % b for b in chunk))
    lines.append("};")
    lines.append("")

    out = "\n".join(lines)
    if os.path.exists(DST):
        with open(DST) as f:
            if f.read() == out:
                return                      # unchanged, keep the timestamp
    with open(DST, "w") as f:
        f.write(out)
    print("embed_webapp: index.html %d B -> %d B gzipped" % (len(raw), len(packed)))


build_header()
